"""initial schema

Revision ID: 073d8334a98a
Revises: 
Create Date: 2026-10-04 11:16:27.934175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '073d8334a98a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('candidate_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('personal_verified', sa.Boolean(), nullable=False),
    sa.Column('kb_version', sa.Integer(), nullable=False),
    sa.Column('kb_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('certifications',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_profile_id'), ['profile_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('collection', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunks_user_collection', ['user_id', 'collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_user_id'), ['user_id'], unique=False)

    op.create_table('experiences',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=40), nullable=True),
    sa.Column('end_date', sa.String(length=40), nullable=True),
    sa.Column('highlights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('technologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_profile_id'), ['profile_id'], unique=False)

    op.create_table('job_descriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('match', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_descriptions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_descriptions_user_id'), ['user_id'], unique=False)

    op.create_table('profile_items',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=60), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_items_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_items_profile_id'), ['profile_id'], unique=False)

    op.create_table('projects',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('candidate_role', sa.Text(), nullable=True),
    sa.Column('architecture', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('technologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('responsibilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('challenges', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('solutions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('limitations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('future_work', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('testing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_profile_id'), ['profile_id'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parse_status', sa.String(length=24), nullable=False),
    sa.Column('parse_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    op.create_table('skills',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'name', name='uq_skill_profile_name')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_profile_id'), ['profile_id'], unique=False)

    op.create_table('interview_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('answer_length', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_sessions_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('question_bank',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=12), nullable=False),
    sa.Column('expected_concepts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resume_relevance', sa.Float(), nullable=False),
    sa.Column('job_relevance', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question', name='uq_bank_user_question')
    )
    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_bank_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_user_id'), ['user_id'], unique=False)

    op.create_table('resume_sections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_sections_resume_id'), ['resume_id'], unique=False)

    op.create_table('interview_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('interview_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_reports_user_id'), ['user_id'], unique=False)

    op.create_table('practice_attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('question_bank_id', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('feedback', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_attempts_question_bank_id'), ['question_bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('resolved_text', sa.Text(), nullable=False),
    sa.Column('qtype', sa.String(length=24), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=True),
    sa.Column('difficulty', sa.String(length=12), nullable=False),
    sa.Column('classification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('focus', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_user_id'), ['user_id'], unique=False)

    op.create_table('session_summaries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('upto_seq', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_summaries_session_id'), ['session_id'], unique=False)

    op.create_table('answers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=20), nullable=False),
    sa.Column('length_target', sa.String(length=12), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('speaking_seconds', sa.Float(), nullable=False),
    sa.Column('key_points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('star', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('grounding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latency', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('insufficient_context', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_user_id'), ['user_id'], unique=False)

    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=True),
    sa.Column('answer_id', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_turn_session_seq')
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_turns_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_turns_session_id'), ['session_id'], unique=False)

    op.create_table('answer_evaluations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('answer_id', sa.String(length=32), nullable=False),
    sa.Column('scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_evaluations_answer_id'), ['answer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_evaluations_answer_id'))

    op.drop_table('answer_evaluations')
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turns_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_turns_question_id'))

    op.drop_table('conversation_turns')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_answers_question_id'))

    op.drop_table('answers')
    with op.batch_alter_table('session_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_summaries_session_id'))

    op.drop_table('session_summaries')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_questions_session_id'))

    op.drop_table('questions')
    with op.batch_alter_table('practice_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_practice_attempts_question_bank_id'))

    op.drop_table('practice_attempts')
    with op.batch_alter_table('interview_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_reports_user_id'))

    op.drop_table('interview_reports')
    with op.batch_alter_table('resume_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_sections_resume_id'))

    op.drop_table('resume_sections')
    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_bank_job_id'))
        batch_op.drop_index(batch_op.f('ix_question_bank_category'))

    op.drop_table('question_bank')
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_job_id'))

    op.drop_table('interview_sessions')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_profile_id'))

    op.drop_table('skills')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))
        batch_op.drop_index(batch_op.f('ix_resumes_document_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_profile_id'))

    op.drop_table('projects')
    with op.batch_alter_table('profile_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_items_profile_id'))
        batch_op.drop_index(batch_op.f('ix_profile_items_kind'))

    op.drop_table('profile_items')
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_descriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_descriptions_document_id'))

    op.drop_table('job_descriptions')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_profile_id'))

    op.drop_table('experiences')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index('ix_chunks_user_collection')

    op.drop_table('document_chunks')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certifications_profile_id'))

    op.drop_table('certifications')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))

    op.drop_table('documents')
    op.drop_table('candidate_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
